@api = http://localhost:3000/api/resources

###
GET {{api}}
###
POST {{api}}
Content-Type: application/json

{
    "name": "Scroll Reveal 3",
    "topicId": "647e85c4c0cef15f3f756556",
    "link": "https://scrollrevealjs.org/",
    "rating": 5
}
###
DELETE {{api}}/647e85e6c0cef15f3f756559