@api = http://localhost:3000/api/topics

###
GET {{api}}
###
GET {{api}}/647a9429d2f4ad86573d5ff8
###
POST {{api}}
Content-Type: application/json

{
    "name": "Java"
}
###
DELETE {{api}}/647a9429d2f4ad86573d5ff8