@api = http://localhost:3000/api/topics

###
GET {{api}}
###
GET {{api}}/647e78c9377aa8703a9c0f64
###
POST {{api}}
Content-Type: application/json

{
    "name": "Animaciones"
}
###
DELETE {{api}}/647e85c4c0cef15f3f756556