@api = http://localhost:3000/api/topics

###
GET {{api}}
###
GET {{api}}/647caa5e85a83d9b49b30d9e
###
POST {{api}}
Content-Type: application/json

{
    "name": "React"
}
###
DELETE {{api}}/647a9429d2f4ad86573d5ff8